// create separate namespace for all the Emscripten stuff.. otherwise naming clashes may occur especially when 
// optimizing using closure compiler..
window.spp_backend_state_XMP= {
	notReady: true,
	adapterCallback: function(){}	// overwritten later	
};
window.spp_backend_state_XMP["onRuntimeInitialized"] = function() {	// emscripten callback needed in case async init is used (e.g. for WASM)
	this.notReady= false;
	this.adapterCallback();
}.bind(window.spp_backend_state_XMP);

var backend_XMP = (function(Module) {var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in e)e.hasOwnProperty(k)&&(aa[k]=e[k]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var l=!1,m=!1,p=!1,ba=!1;l="object"===typeof window;m="function"===typeof importScripts;p="object"===typeof process&&"function"===typeof require&&!l&&!m;ba=!l&&!p&&!m;var r="";function ca(a){return e.locateFile?e.locateFile(a,r):r+a}
if(p){r=__dirname+"/";var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",
t);e.quit=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(ba)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(l||m)m?
r=self.location.href:document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.lastIndexOf("/")+1):"",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==
d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var fa=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),u=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(k in aa)aa.hasOwnProperty(k)&&(e[k]=aa[k]);aa=void 0;function ha(a){var b=x;x=x+a+15&-16;return b}
function ia(a){var b=y[z>>2];a=b+a+15&-16;y[z>>2]=a;if(a=a>=A)ja(),a=!0;return a?(y[z>>2]=b,0):b}function ka(a){var b;b||(b=16);return Math.ceil(a/b)*b}var la={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},ma=!1;function assert(a,b){a||t("Assertion failed: "+b)}
var ra={stackSave:function(){na()},stackRestore:function(){oa()},arrayToC:function(a){var b=pa(a.length);B.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=pa(c);qa(a,C,b,c)}return b}},sa={string:ra.stringToC,array:ra.arrayToC};
function ta(a,b){if("number"===typeof a){var c=!0;var d=a}else c=!1,d=a.length;b=4==b?f:["function"===typeof ua?ua:ha,pa,ha,ia][void 0===b?2:b](Math.max(d,1));if(c){var f=b;assert(0==(b&3));for(a=b+(d&-4);f<a;f+=4)y[f>>2]=0;for(a=b+d;f<a;)B[f++>>0]=0;return b}a.subarray||a.slice?C.set(a,b):C.set(new Uint8Array(a),b);return b}function va(a){return wa?ya?ua(a):ia(a):ha(a)}
function D(a,b){if(0===b||!a)return"";for(var c=0,d,f=0;;){d=C[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,C.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return za(C,a)}var Aa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Aa)return Aa.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;if(224==(d&240))d=(d&15)<<12|f<<6|g;else{var h=a[b++]&63;if(240==(d&248))d=(d&7)<<18|f<<12|g<<6|h;else{var n=a[b++]&63;if(248==(d&252))d=(d&3)<<24|f<<18|g<<12|h<<6|n;else{var q=a[b++]&63;d=(d&1)<<30|f<<24|g<<18|h<<12|n<<6|q}}}65536>d?c+=String.fromCharCode(d):(d-=
65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}
function qa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(2097151>=h){if(c+3>=d)break;b[c++]=240|h>>18}else{if(67108863>=h){if(c+4>=d)break;b[c++]=248|h>>24}else{if(c+5>=d)break;b[c++]=252|h>>30;b[c++]=128|h>>24&63}b[c++]=128|h>>18&63}b[c++]=
128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var buffer,B,C,Ca,y;
function Da(){e.HEAP8=B=new Int8Array(buffer);e.HEAP16=Ca=new Int16Array(buffer);e.HEAP32=y=new Int32Array(buffer);e.HEAPU8=C=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=new Float32Array(buffer);e.HEAPF64=new Float64Array(buffer)}var Ea,x,wa,Fa,Ga,Ha,Ia,z;Ea=x=Fa=Ga=Ha=Ia=z=0;wa=!1;
function ja(){t("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+A+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var Ja=e.TOTAL_STACK||5242880,A=e.TOTAL_MEMORY||100663296;A<Ja&&u("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+A+"! (TOTAL_STACK="+Ja+")");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:A/65536,maximum:A/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(A),e.buffer=buffer);Da();function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Da;"number"===typeof c?void 0===b.Y?e.dynCall_v(c):e.dynCall_vi(c,b.Y):c(void 0===b.Y?null:b.Y)}}}var La=[],Ma=[],Na=[],Oa=[],Pa=[],ya=!1;
function Qa(){var a=e.preRun.shift();La.unshift(a)}var E=0,Ra=null,Sa=null;function Ta(){E++;e.monitorRunDependencies&&e.monitorRunDependencies(E)}function Ua(){E--;e.monitorRunDependencies&&e.monitorRunDependencies(E);if(0==E&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}e.preloadedImages={};e.preloadedAudios={};function Xa(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(f);throw"both async and sync fetching of the wasm failed";}catch(w){t(w)}}function b(){return e.wasmBinary||!l&&!m||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(f,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+f+"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){n=a.exports;if(n.memory){a=
n.memory;var b=e.buffer;a.byteLength<b.byteLength&&u("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);e.buffer=buffer=a;Da()}e.asm=n;e.usingWasm=!0;Ua()}function d(a){c(a.instance)}function g(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){u("failed to asynchronously prepare wasm: "+a);t(a)})}if("object"!==typeof WebAssembly)return u("no native wasm support detected"),
!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return u("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;Ta();if(e.instantiateWasm)try{return e.instantiateWasm(h,c)}catch(P){return u("Module.instantiateWasm callback failed with error: "+P),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Xa(f)||"function"!==typeof fetch?g(d):WebAssembly.instantiateStreaming(fetch(f,{credentials:"same-origin"}),h).then(d,
function(a){u("wasm streaming compile failed: "+a);u("falling back to ArrayBuffer instantiation");g(d)});return{}}var d="xmp.wast",f="xmp.wasm",g="xmp.temp.asm.js";Xa(d)||(d=ca(d));Xa(f)||(f=ca(f));Xa(g)||(g=ca(g));var h={global:null,env:null,asm2wasm:la,parent:e},n=null;e.asmPreload=e.asm;var q=e.reallocBuffer;e.reallocBuffer=function(a){if("asmjs"===v)var b=q(a);else a:{var c=e.usingWasm?65536:16777216;0<a%c&&(a+=c-a%c);c=e.buffer.byteLength;if(e.usingWasm)try{b=-1!==e.wasmMemory.grow((a-c)/65536)?
e.buffer=e.wasmMemory.buffer:null;break a}catch(xa){b=null;break a}b=void 0}return b};var v="";e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;void 0===a&&(a=1024);var d=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==d?new WebAssembly.Table({initial:a,maximum:d,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.memoryBase||(b.memoryBase=e.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);
assert(b,"no binaryen method succeeded.");return b}})();Ea=1024;x=Ea+462800;Ma.push({Da:function(){Ya()}});e.STATIC_BASE=Ea;e.STATIC_BUMP=462800;x+=16;var F={};
function Za(a){if(Za.H){var b=y[a>>2];var c=y[b>>2]}else Za.H=!0,F.USER=F.LOGNAME="web_user",F.PATH="/",F.PWD="/",F.HOME="/home/web_user",F.LANG="C.UTF-8",F._=e.thisProgram,c=va(1024),b=va(256),y[b>>2]=c,y[a>>2]=b;a=[];var d=0,f;for(f in F)if("string"===typeof F[f]){var g=f+"="+F[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,n=0;n<d.length;++n)B[h++>>0]=d.charCodeAt(n);B[h>>0]=0;y[b+4*f>>2]=c;c+=g.length+1}y[b+
4*a.length>>2]=0}function G(){t()}
var H={D:1,u:2,zc:3,vb:4,B:5,ga:6,Oa:7,Tb:8,v:9,bb:10,da:11,Jc:11,wa:12,U:13,ob:14,ec:15,V:16,ea:17,Kc:18,X:19,P:20,K:21,h:22,Ob:23,va:24,C:25,Gc:26,pb:27,ac:28,R:29,wc:30,Hb:31,pc:32,lb:33,tc:34,Xb:42,sb:43,cb:44,yb:45,zb:46,Ab:47,Gb:48,Hc:49,Rb:50,xb:51,ib:35,Ub:37,Ua:52,Xa:53,Lc:54,Pb:55,Ya:56,Za:57,jb:35,$a:59,cc:60,Sb:61,Dc:62,bc:63,Yb:64,Zb:65,vc:66,Vb:67,Ra:68,Ac:69,eb:70,qc:71,Jb:72,mb:73,Wa:74,kc:76,Va:77,uc:78,Bb:79,Cb:80,Fb:81,Eb:82,Db:83,dc:38,fa:39,Kb:36,W:40,lc:95,oc:96,hb:104,Qb:105,
Sa:97,sc:91,ic:88,$b:92,xc:108,gb:111,Pa:98,fb:103,Nb:101,Lb:100,Ec:110,qb:112,rb:113,ub:115,Ta:114,kb:89,Ib:90,rc:93,yc:94,Qa:99,Mb:102,wb:106,fc:107,Fc:109,Ic:87,nb:122,Bc:116,jc:95,Wb:123,tb:84,mc:75,ab:125,hc:131,nc:130,Cc:86};function $a(a){e.___errno_location&&(y[e.___errno_location()>>2]=a);return a}
function ab(a,b){if(0===a)a=Date.now();else if(1===a&&(p||"undefined"!==typeof dateNow||(l||m)&&self.performance&&self.performance.now))a=G();else return $a(H.h),-1;y[b>>2]=a/1E3|0;y[b+4>>2]=a%1E3*1E6|0;return 0}
var bb={0:"Success",1:"Not super-user",2:"No such file or directory",3:"No such process",4:"Interrupted system call",5:"I/O error",6:"No such device or address",7:"Arg list too long",8:"Exec format error",9:"Bad file number",10:"No children",11:"No more processes",12:"Not enough core",13:"Permission denied",14:"Bad address",15:"Block device required",16:"Mount device busy",17:"File exists",18:"Cross-device link",19:"No such device",20:"Not a directory",21:"Is a directory",22:"Invalid argument",23:"Too many open files in system",
24:"Too many open files",25:"Not a typewriter",26:"Text file busy",27:"File too large",28:"No space left on device",29:"Illegal seek",30:"Read only file system",31:"Too many links",32:"Broken pipe",33:"Math arg out of domain of func",34:"Math result not representable",35:"File locking deadlock error",36:"File or path name too long",37:"No record locks available",38:"Function not implemented",39:"Directory not empty",40:"Too many symbolic links",42:"No message of desired type",43:"Identifier removed",
44:"Channel number out of range",45:"Level 2 not synchronized",46:"Level 3 halted",47:"Level 3 reset",48:"Link number out of range",49:"Protocol driver not attached",50:"No CSI structure available",51:"Level 2 halted",52:"Invalid exchange",53:"Invalid request descriptor",54:"Exchange full",55:"No anode",56:"Invalid request code",57:"Invalid slot",59:"Bad font file fmt",60:"Device not a stream",61:"No data (for no delay io)",62:"Timer expired",63:"Out of streams resources",64:"Machine is not on the network",
65:"Package not installed",66:"The object is remote",67:"The link has been severed",68:"Advertise error",69:"Srmount error",70:"Communication error on send",71:"Protocol error",72:"Multihop attempted",73:"Cross mount point (not really error)",74:"Trying to read unreadable message",75:"Value too large for defined data type",76:"Given log. name not unique",77:"f.d. invalid for this operation",78:"Remote address changed",79:"Can   access a needed shared lib",80:"Accessing a corrupted shared lib",81:".lib section in a.out corrupted",
82:"Attempting to link in too many libs",83:"Attempting to exec a shared library",84:"Illegal byte sequence",86:"Streams pipe error",87:"Too many users",88:"Socket operation on non-socket",89:"Destination address required",90:"Message too long",91:"Protocol wrong type for socket",92:"Protocol not available",93:"Unknown protocol",94:"Socket type not supported",95:"Not supported",96:"Protocol family not supported",97:"Address family not supported by protocol family",98:"Address already in use",99:"Address not available",
100:"Network interface is not configured",101:"Network is unreachable",102:"Connection reset by network",103:"Connection aborted",104:"Connection reset by peer",105:"No buffer space available",106:"Socket is already connected",107:"Socket is not connected",108:"Can't send after socket shutdown",109:"Too many references",110:"Connection timed out",111:"Connection refused",112:"Host is down",113:"Host is unreachable",114:"Socket already connected",115:"Connection already in progress",116:"Stale file handle",
122:"Quota exceeded",123:"No medium (in tape drive)",125:"Operation canceled",130:"Previous owner died",131:"State not recoverable"};function cb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function db(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function eb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function gb(){var a=Array.prototype.slice.call(arguments,0);return db(a.join("/"))}function I(a,b){return db(a+"/"+b)}
function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=cb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var ib=[];function jb(a,b){ib[a]={input:[],output:[],J:b};kb(a,lb)}
var lb={open:function(a){var b=ib[a.node.rdev];if(!b)throw new J(H.X);a.tty=b;a.seekable=!1},close:function(a){a.tty.J.flush(a.tty)},flush:function(a){a.tty.J.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.J.pa)throw new J(H.ga);for(var f=0,g=0;g<d;g++){try{var h=a.tty.J.pa(a.tty)}catch(n){throw new J(H.B);}if(void 0===h&&0===f)throw new J(H.da);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.J.aa)throw new J(H.ga);
for(var f=0;f<d;f++)try{a.tty.J.aa(a.tty,b[c+f])}catch(g){throw new J(H.B);}d&&(a.node.timestamp=Date.now());return f}},nb={pa:function(a){if(!a.input.length){var b=null;if(p){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=mb(b,!0)}return a.input.shift()},aa:function(a,b){null===b||10===b?(fa(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(fa(za(a.output,0)),a.output=[])}},ob={aa:function(a,b){null===b||10===b?(u(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(u(za(a.output,0)),a.output=[])}},K={s:null,j:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(H.D);K.s||(K.s={dir:{node:{o:K.c.o,i:K.c.i,lookup:K.c.lookup,M:K.c.M,rename:K.c.rename,unlink:K.c.unlink,rmdir:K.c.rmdir,readdir:K.c.readdir,symlink:K.c.symlink},stream:{A:K.f.A}},file:{node:{o:K.c.o,i:K.c.i},stream:{A:K.f.A,read:K.f.read,write:K.f.write,ha:K.f.ha,sa:K.f.sa,ua:K.f.ua}},link:{node:{o:K.c.o,i:K.c.i,
readlink:K.c.readlink},stream:{}},ka:{node:{o:K.c.o,i:K.c.i},stream:pb}});c=qb(a,b,c,d);M(c.mode)?(c.c=K.s.dir.node,c.f=K.s.dir.stream,c.b={}):32768===(c.mode&61440)?(c.c=K.s.file.node,c.f=K.s.file.stream,c.g=0,c.b=null):40960===(c.mode&61440)?(c.c=K.s.link.node,c.f=K.s.link.stream):8192===(c.mode&61440)&&(c.c=K.s.ka.node,c.f=K.s.ka.stream);c.timestamp=Date.now();a&&(a.b[b]=c);return c},Ea:function(a){if(a.b&&a.b.subarray){for(var b=[],c=0;c<a.g;++c)b.push(a.b[c]);return b}return a.b},Oc:function(a){return a.b?
a.b.subarray?a.b.subarray(0,a.g):new Uint8Array(a.b):new Uint8Array},la:function(a,b){a.b&&a.b.subarray&&b>a.b.length&&(a.b=K.Ea(a),a.g=a.b.length);if(!a.b||a.b.subarray){var c=a.b?a.b.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.b,a.b=new Uint8Array(b),0<a.g&&a.b.set(c.subarray(0,a.g),0))}else for(!a.b&&0<b&&(a.b=[]);a.b.length<b;)a.b.push(0)},Ja:function(a,b){if(a.g!=b)if(0==b)a.b=null,a.g=0;else{if(!a.b||a.b.subarray){var c=a.b;a.b=new Uint8Array(new ArrayBuffer(b));
c&&a.b.set(c.subarray(0,Math.min(b,a.g)))}else if(a.b||(a.b=[]),a.b.length>b)a.b.length=b;else for(;a.b.length<b;)a.b.push(0);a.g=b}},c:{o:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;M(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.g:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.F=4096;b.blocks=Math.ceil(b.size/b.F);return b},
i:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Ja(a,b.size)},lookup:function(){throw rb[H.u];},M:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(M(a.mode)){try{var d=N(b,c)}catch(g){}if(d)for(var f in d.b)throw new J(H.fa);}delete a.parent.b[a.name];a.name=c;b.b[c]=a;a.parent=b},unlink:function(a,b){delete a.b[b]},rmdir:function(a,b){var c=N(a,b),d;for(d in c.b)throw new J(H.fa);delete a.b[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.b)a.b.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(H.h);return a.link}},f:{read:function(a,b,c,d,f){var g=a.node.b;if(f>=a.node.g)return 0;a=Math.min(a.node.g-f,d);assert(0<=a);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&
(!a.b||a.b.subarray)){if(g)return a.b=b.subarray(c,c+d),a.g=d;if(0===a.g&&0===f)return a.b=new Uint8Array(b.subarray(c,c+d)),a.g=d;if(f+d<=a.g)return a.b.set(b.subarray(c,c+d),f),d}K.la(a,f+d);if(a.b.subarray&&b.subarray)a.b.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.b[f+g]=b[c+g];a.g=Math.max(a.g,f+d);return d},A:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.g);if(0>b)throw new J(H.h);return b},ha:function(a,b,c){K.la(a.node,b+c);a.node.g=Math.max(a.node.g,
b+c)},sa:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new J(H.X);c=a.node.b;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.g)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=ua(d);if(!d)throw new J(H.wa);b.set(c,d)}else a=!1,d=c.byteOffset;return{Qc:d,Mc:a}},ua:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new J(H.X);if(f&2)return 0;K.f.write(a,b,0,d,c,!1);return 0}}},O={T:!1,Ma:function(){O.T=!!process.platform.match(/^win/);var a=
process.binding("constants");a.fs&&(a=a.fs);O.ma={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},ia:function(a){return Buffer.H?Buffer.from(a):new Buffer(a)},j:function(a){assert(p);return O.createNode(null,"/",O.oa(a.$.root),0)},createNode:function(a,b,c){if(!M(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new J(H.h);a=qb(a,b,c);a.c=O.c;a.f=O.f;return a},oa:function(a){try{var b=fs.lstatSync(a);O.T&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;
throw new J(H[c.code]);}return b.mode},l:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.j.$.root);b.reverse();return gb.apply(null,b)},Ca:function(a){a&=-2656257;var b=0,c;for(c in O.ma)a&c&&(b|=O.ma[c],a^=c);if(a)throw new J(H.h);return b},c:{o:function(a){a=O.l(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}O.T&&!b.F&&(b.F=4096);O.T&&!b.blocks&&(b.blocks=(b.size+b.F-1)/b.F|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,
gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,F:b.F,blocks:b.blocks}},i:function(a,b){var c=O.l(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new J(H[d.code]);}},lookup:function(a,b){var c=I(O.l(a),b);c=O.oa(c);return O.createNode(a,b,c)},M:function(a,b,c,d){a=O.createNode(a,b,c,d);b=O.l(a);try{M(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;
throw new J(H[f.code]);}return a},rename:function(a,b,c){a=O.l(a);b=I(O.l(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new J(H[d.code]);}},unlink:function(a,b){a=I(O.l(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}},rmdir:function(a,b){a=I(O.l(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}},readdir:function(a){a=O.l(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new J(H[b.code]);}},symlink:function(a,
b,c){a=I(O.l(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new J(H[d.code]);}},readlink:function(a){var b=O.l(a);try{return b=fs.readlinkSync(b),b=sb.relative(sb.resolve(a.j.$.root),b)}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}}},f:{open:function(a){var b=O.l(a.node);try{32768===(a.node.mode&61440)&&(a.O=fs.openSync(b,O.Ca(a.flags)))}catch(c){if(!c.code)throw c;throw new J(H[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.O&&fs.closeSync(a.O)}catch(b){if(!b.code)throw b;
throw new J(H[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.O,O.ia(b.buffer),c,d,f)}catch(g){throw new J(H[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.O,O.ia(b.buffer),c,d,f)}catch(g){throw new J(H[g.code]);}},A:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.O).size}catch(d){throw new J(H[d.code]);}if(0>b)throw new J(H.h);return b}}};x+=16;x+=16;x+=16;
var tb=null,ub={},Q=[],vb=1,R=null,wb=!0,S={},J=null,rb={};
function T(a,b){a=hb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={na:!0,ba:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ba)throw new J(H.W);a=cb(a.split("/").filter(function(a){return!!a}),!1);var f=tb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=N(f,a[d]);c=I(c,a[d]);f.N&&(!g||g&&b.na)&&(f=f.N.root);if(!g||b.L)for(g=0;40960===(f.mode&61440);)if(f=xb(c),c=hb(eb(c),f),f=T(c,{ba:b.ba}).node,40<g++)throw new J(H.W);}return{path:c,node:f}}
function U(a){for(var b;;){if(a===a.parent)return a=a.j.ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function yb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function zb(a){var b=yb(a.parent.id,a.name);a.I=R[b];R[b]=a}function N(a,b){var c;if(c=(c=Ab(a,"x"))?c:a.c.lookup?0:H.U)throw new J(c,a);for(c=R[yb(a.id,b)];c;c=c.I){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.c.lookup(a,b)}
function qb(a,b,c,d){Bb||(Bb=function(a,b,c,d){a||(a=this);this.parent=a;this.j=a.j;this.N=null;this.id=vb++;this.name=b;this.mode=c;this.c={};this.f={};this.rdev=d},Bb.prototype={},Object.defineProperties(Bb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ha:{get:function(){return M(this.mode)}},Ga:{get:function(){return 8192===(this.mode&
61440)}}}));a=new Bb(a,b,c,d);zb(a);return a}function M(a){return 16384===(a&61440)}var Cb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Db(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ab(a,b){if(wb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return H.U}else return H.U;return 0}
function Eb(a,b){try{return N(a,b),H.ea}catch(c){}return Ab(a,"wx")}function Fb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new J(H.va);}function Gb(a,b){Hb||(Hb=function(){},Hb.prototype={},Object.defineProperties(Hb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Hb,d;for(d in a)c[d]=a[d];a=c;b=Fb(b);a.fd=b;return Q[b]=a}var pb={open:function(a){a.f=ub[a.node.rdev].f;a.f.open&&a.f.open(a)},A:function(){throw new J(H.R);}};
function kb(a,b){ub[a]={f:b}}function Ib(a,b){var c="/"===b,d=!b;if(c&&tb)throw new J(H.V);if(!c&&!d){var f=T(b,{na:!1});b=f.path;f=f.node;if(f.N)throw new J(H.V);if(!M(f.mode))throw new J(H.P);}b={type:a,$:{},ta:b,Ia:[]};a=a.j(b);a.j=b;b.root=a;c?tb=a:f&&(f.N=b,f.j&&f.j.Ia.push(b))}function Jb(a,b,c){var d=T(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new J(H.h);var f=Eb(d,a);if(f)throw new J(f);if(!d.c.M)throw new J(H.D);return d.c.M(d,a,b,c)}
function V(a,b){return Jb(a,(void 0!==b?b:511)&1023|16384,0)}function Kb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Jb(a,b|8192,c)}function Lb(a,b){if(!hb(a))throw new J(H.u);var c=T(b,{parent:!0}).node;if(!c)throw new J(H.u);b=fb(b);var d=Eb(c,b);if(d)throw new J(d);if(!c.c.symlink)throw new J(H.D);return c.c.symlink(c,b,a)}
function Mb(a){var b=T(a,{parent:!0}).node,c=fb(a),d=N(b,c);a:{try{var f=N(b,c)}catch(h){f=h.m;break a}var g=Ab(b,"wx");f=g?g:M(f.mode)?H.K:0}if(f)throw new J(f);if(!b.c.unlink)throw new J(H.D);if(d.N)throw new J(H.V);try{S.willDeletePath&&S.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.c.unlink(b,c);b=yb(d.parent.id,d.name);if(R[b]===d)R[b]=d.I;else for(b=R[b];b;){if(b.I===d){b.I=d.I;break}b=b.I}try{if(S.onDeletePath)S.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function xb(a){a=T(a).node;if(!a)throw new J(H.u);if(!a.c.readlink)throw new J(H.h);return hb(U(a.parent),a.c.readlink(a))}function Nb(a,b){var c;"string"===typeof a?c=T(a,{L:!0}).node:c=a;if(!c.c.i)throw new J(H.D);c.c.i(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Ob(a,b,c,d){if(""===a)throw new J(H.u);if("string"===typeof b){var f=Cb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=db(a);try{g=T(a,{L:!(b&131072)}).node}catch(q){}}f=!1;if(b&64)if(g){if(b&128)throw new J(H.ea);}else g=Jb(a,c,0),f=!0;if(!g)throw new J(H.u);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!M(g.mode))throw new J(H.P);if(!f){var h=g?40960===(g.mode&61440)?H.W:
M(g.mode)&&("r"!==Db(b)||b&512)?H.K:Ab(g,Db(b)):H.u;if(h)throw new J(h);}if(b&512){c=g;var n;"string"===typeof c?n=T(c,{L:!0}).node:n=c;if(!n.c.i)throw new J(H.D);if(M(n.mode))throw new J(H.K);if(32768!==(n.mode&61440))throw new J(H.h);if(c=Ab(n,"w"))throw new J(c);n.c.i(n,{size:0,timestamp:Date.now()})}b&=-641;d=Gb({node:g,path:U(g),flags:b,seekable:!0,position:0,f:g.f,Na:[],error:!1},d);d.f.open&&d.f.open(d);!e.logReadFiles||b&1||(Pb||(Pb={}),a in Pb||(Pb[a]=1,h("read file: "+a)));try{S.onOpenFile&&
(h=0,1!==(b&2097155)&&(h|=1),0!==(b&2097155)&&(h|=2),S.onOpenFile(a,h))}catch(q){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+q.message)}return d}function Qb(a){if(null===a.fd)throw new J(H.v);a.G&&(a.G=null);try{a.f.close&&a.f.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}a.fd=null}function Rb(a,b,c){if(null===a.fd)throw new J(H.v);if(!a.seekable||!a.f.A)throw new J(H.R);a.position=a.f.A(a,b,c);a.Na=[]}
function Sb(a,b,c,d,f,g){if(0>d||0>f)throw new J(H.h);if(null===a.fd)throw new J(H.v);if(0===(a.flags&2097155))throw new J(H.v);if(M(a.node.mode))throw new J(H.K);if(!a.f.write)throw new J(H.h);a.flags&1024&&Rb(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new J(H.R);b=a.f.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&S.onWriteToFile)S.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+n.message)}return b}
function Tb(){J||(J=function(a,b){this.node=b;this.La=function(a){this.m=a;for(var b in H)if(H[b]===a){this.code=b;break}};this.La(a);this.message=bb[a];this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},J.prototype=Error(),J.prototype.constructor=J,[H.u].forEach(function(a){rb[a]=new J(a);rb[a].stack="<generic error, no stack>"}))}var Ub;function Vb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Wb(a,b,c,d){a=I("string"===typeof a?a:U(a),b);return V(a,Vb(c,d))}function Xb(a,b){a="string"===typeof a?a:U(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=I(a,c);try{V(d)}catch(f){}a=d}}return d}function Yb(a,b,c,d){a=I("string"===typeof a?a:U(a),b);c=Vb(c,d);return Jb(a,(void 0!==c?c:438)&4095|32768,0)}
function Zb(a,b,c,d,f,g){a=b?I("string"===typeof a?a:U(a),b):a;d=Vb(d,f);f=Jb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Nb(f,d|146);a=Ob(f,"w");Sb(a,c,0,c.length,0,g);Qb(a);Nb(f,d)}return f}
function W(a,b,c,d){a=I("string"===typeof a?a:U(a),b);b=Vb(!!c,!!d);W.ra||(W.ra=64);var f=W.ra++<<8|0;kb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var n=c()}catch(Wa){throw new J(H.B);}if(void 0===n&&0===g)throw new J(H.da);if(null===n||void 0===n)break;g++;b[d+h]=n}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(w){throw new J(H.B);}f&&(a.node.timestamp=
Date.now());return g}});return Kb(a,b,f)}function $b(a,b,c){a=I("string"===typeof a?a:U(a),b);return Lb(c,a)}
function ac(a){if(a.Ga||a.Ha||a.link||a.b)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.b=mb(e.read(a.url),!0),a.g=a.b.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||$a(H.B);return b}
function bc(a,b,c,d,f){function g(){this.Z=!1;this.S=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.qa(a/this.chunkSize|0)[b]}};g.prototype.Ka=function(a){this.qa=a};g.prototype.ja=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&"bytes"===
d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.Ka(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.S[a]){var n=h.S;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var q=new XMLHttpRequest;q.open("GET",c,!1);b!==g&&q.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(q.responseType="arraybuffer");q.overrideMimeType&&
q.overrideMimeType("text/plain; charset=x-user-defined");q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);d=void 0!==q.response?new Uint8Array(q.response||[]):mb(q.responseText||"",!0);n[a]=d}if("undefined"===typeof h.S[a])throw Error("doXHR failed!");return h.S[a]});if(a||!b)g=b=1,g=b=this.qa(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.za=b;this.ya=g;this.Z=!0};if("undefined"!==
typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.Z||this.ja();return this.za}},chunkSize:{get:function(){this.Z||this.ja();return this.ya}}});var n=void 0}else n=c,h=void 0;var q=Yb(a,b,d,f);h?q.b=h:n&&(q.b=null,q.url=n);Object.defineProperties(q,{g:{get:function(){return this.b.length}}});var v={};Object.keys(q.f).forEach(function(a){var b=
q.f[a];v[a]=function(){if(!ac(q))throw new J(H.B);return b.apply(null,arguments)}});v.read=function(a,b,c,d,f){if(!ac(q))throw new J(H.B);a=a.node.b;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var g=0;g<d;g++)b[c+g]=a[f+g];else for(g=0;g<d;g++)b[c+g]=a.get(f+g);return d};q.f=v;return q}
function cc(a,b,c,d,f,g,h,n,q,v){function w(c){function w(c){v&&v();n||Zb(a,b,c,d,f,q);g&&g();Ua()}var P=!1;e.preloadPlugins.forEach(function(a){!P&&a.canHandle(L)&&(a.handle(c,L,w,function(){h&&h();Ua()}),P=!0)});P||w(c)}Browser.Pc();var L=b?hb(I(a,b)):a;Ta();"string"==typeof c?Browser.Nc(c,function(a){w(a)},h):w(c)}var FS={},Bb,Hb,Pb,X=0;function Y(){X+=4;return y[X-4>>2]}function Z(){var a=Q[Y()];if(!a)throw new J(H.v);return a}
function dc(a){if(0===a)return 0;a=D(a);if(!F.hasOwnProperty(a))return 0;dc.H&&ec(dc.H);a=F[a];var b=Ba(a)+1,c=ua(b);c&&qa(a,B,c,b);dc.H=c;return dc.H}function fc(a){return Math.pow(2,a)}ta(mb("GMT"),2);
function hc(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!ic){ic=!0;y[jc()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),c=new Date(2E3,6,1);y[kc()>>2]=Number(b.getTimezoneOffset()!=c.getTimezoneOffset());var d=a(b),f=a(c);d=ta(mb(d),0);f=ta(mb(f),0);c.getTimezoneOffset()<b.getTimezoneOffset()?(y[lc()>>2]=d,y[lc()+4>>2]=f):(y[lc()>>2]=f,y[lc()+4>>2]=d)}}var ic;
p?G=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?G=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?G=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?G=function(){return performance.now()}:G=Date.now;Tb();R=Array(4096);Ib(K,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");kb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Kb("/dev/null",259);jb(1280,nb);jb(1536,ob);Kb("/dev/tty",1280);Kb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else p?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){t("random_device")};W("/dev","random",b);W("/dev","urandom",b);V("/dev/shm");V("/dev/shm/tmp")})();V("/proc");V("/proc/self");V("/proc/self/fd");
Ib({j:function(){var a=qb("/proc/self","fd",16895,73);a.c={lookup:function(a,c){var b=Q[+c];if(!b)throw new J(H.v);a={parent:null,j:{ta:"fake"},c:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ma.unshift(function(){if(!e.noFSInit&&!Ub){assert(!Ub,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Ub=!0;Tb();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?W("/dev","stdin",e.stdin):Lb("/dev/tty","/dev/stdin");e.stdout?W("/dev","stdout",null,e.stdout):Lb("/dev/tty","/dev/stdout");e.stderr?W("/dev","stderr",null,e.stderr):Lb("/dev/tty1","/dev/stderr");var a=
Ob("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Ob("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Ob("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Na.push(function(){wb=!1});Oa.push(function(){Ub=!1;var a=e._fflush;a&&a(0);for(a=0;a<Q.length;a++){var b=Q[a];b&&Qb(b)}});e.FS_createFolder=Wb;e.FS_createPath=Xb;e.FS_createDataFile=Zb;e.FS_createPreloadedFile=cc;e.FS_createLazyFile=bc;e.FS_createLink=$b;
e.FS_createDevice=W;e.FS_unlink=Mb;Ma.unshift(function(){});Oa.push(function(){});if(p){var fs=require("fs"),sb=require("path");O.Ma()}z=ha(4);Fa=Ga=ka(x);Ha=Fa+Ja;Ia=ka(Ha);y[z>>2]=Ia;wa=!0;function mb(a,b){var c=Array(Ba(a)+1);a=qa(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=484;e.wasmMaxTableSize=484;e.Aa={};
e.Ba={abort:t,enlargeMemory:function(){ja()},getTotalMemory:function(){return A},abortOnCannotGrowMemory:ja,___buildEnvironment:Za,___clock_gettime:function(){return ab.apply(null,arguments)},___lock:function(){},___setErrNo:$a,___syscall10:function(a,b){X=b;try{var c=D(Y());Mb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof J||t(d),-d.m}},___syscall140:function(a,b){X=b;try{var c=Z();Y();var d=Y(),f=Y(),g=Y();Rb(c,d,g);y[f>>2]=c.position;c.G&&0===d&&0===g&&(c.G=null);return 0}catch(h){return"undefined"!==
typeof FS&&h instanceof J||t(h),-h.m}},___syscall145:function(a,b){X=b;try{var c=Z(),d=Y();a:{var f=Y();for(b=a=0;b<f;b++){var g=y[d+(8*b+4)>>2],h=c,n=y[d+8*b>>2],q=g,v=void 0,w=B;if(0>q||0>v)throw new J(H.h);if(null===h.fd)throw new J(H.v);if(1===(h.flags&2097155))throw new J(H.v);if(M(h.node.mode))throw new J(H.K);if(!h.f.read)throw new J(H.h);var L="undefined"!==typeof v;if(!L)v=h.position;else if(!h.seekable)throw new J(H.R);var Wa=h.f.read(h,w,n,q,v);L||(h.position+=Wa);var xa=Wa;if(0>xa){var P=
-1;break a}a+=xa;if(xa<g)break}P=a}return P}catch(Va){return"undefined"!==typeof FS&&Va instanceof J||t(Va),-Va.m}},___syscall146:function(a,b){X=b;try{var c=Z(),d=Y();a:{var f=Y();for(b=a=0;b<f;b++){var g=Sb(c,B,y[d+8*b>>2],y[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(n){return"undefined"!==typeof FS&&n instanceof J||t(n),-n.m}},___syscall195:function(a,b){X=b;try{var c=D(Y());a:{var d=Y();try{var f=T(c,{L:!0}).node;if(!f)throw new J(H.u);if(!f.c.o)throw new J(H.D);var g=
f.c.o(f)}catch(n){if(n&&n.node&&db(c)!==db(U(n.node))){var h=-H.P;break a}throw n;}y[d>>2]=g.dev;y[d+4>>2]=0;y[d+8>>2]=g.ino;y[d+12>>2]=g.mode;y[d+16>>2]=g.nlink;y[d+20>>2]=g.uid;y[d+24>>2]=g.gid;y[d+28>>2]=g.rdev;y[d+32>>2]=0;y[d+36>>2]=g.size;y[d+40>>2]=4096;y[d+44>>2]=g.blocks;y[d+48>>2]=g.atime.getTime()/1E3|0;y[d+52>>2]=0;y[d+56>>2]=g.mtime.getTime()/1E3|0;y[d+60>>2]=0;y[d+64>>2]=g.ctime.getTime()/1E3|0;y[d+68>>2]=0;y[d+72>>2]=g.ino;h=0}return h}catch(n){return"undefined"!==typeof FS&&n instanceof
J||t(n),-n.m}},___syscall220:function(a,b){X=b;try{var c=Z(),d=Y(),f=Y();if(!c.G){var g=T(c.path,{L:!0}).node;if(!g.c.readdir)throw new J(H.P);var h=g.c.readdir(g);c.G=h}for(a=0;0<c.G.length&&a+268<=f;){var n=c.G.pop();if("."===n[0]){var q=1;var v=4}else{var w=N(c.node,n);q=w.id;v=8192===(w.mode&61440)?2:M(w.mode)?4:40960===(w.mode&61440)?10:8}y[d+a>>2]=q;y[d+a+4>>2]=c.position;Ca[d+a+8>>1]=268;B[d+a+10>>0]=v;qa(n,C,d+a+11,256);a+=268}return a}catch(L){return"undefined"!==typeof FS&&L instanceof J||
t(L),-L.m}},___syscall221:function(a,b){X=b;try{var c=Z();switch(Y()){case 0:var d=Y();return 0>d?-H.h:Ob(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=Y(),c.flags|=d,0;case 12:case 12:return d=Y(),Ca[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-H.h;case 9:return $a(H.h),-1;default:return-H.h}}catch(f){return"undefined"!==typeof FS&&f instanceof J||t(f),-f.m}},___syscall5:function(a,b){X=b;try{var c=D(Y()),d=Y(),f=Y();return Ob(c,
d,f).fd}catch(g){return"undefined"!==typeof FS&&g instanceof J||t(g),-g.m}},___syscall54:function(a,b){X=b;try{var c=Z(),d=Y();switch(d){case 21509:case 21505:return c.tty?0:-H.C;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-H.C;case 21519:if(!c.tty)return-H.C;var f=Y();return y[f>>2]=0;case 21520:return c.tty?-H.h:-H.C;case 21531:a=f=Y();if(!c.f.Fa)throw new J(H.C);return c.f.Fa(c,d,a);case 21523:return c.tty?0:-H.C;case 21524:return c.tty?0:-H.C;default:t("bad ioctl syscall "+
d)}}catch(g){return"undefined"!==typeof FS&&g instanceof J||t(g),-g.m}},___syscall6:function(a,b){X=b;try{var c=Z();Qb(c);return 0}catch(d){return"undefined"!==typeof FS&&d instanceof J||t(d),-d.m}},___unlock:function(){},_emscripten_memcpy_big:function(a,b,c){C.set(C.subarray(b,b+c),a);return a},_getenv:dc,_llvm_exp2_f32:fc,_llvm_exp2_f64:function(){return fc.apply(null,arguments)},_localtime_r:function(a,b){hc();a=new Date(1E3*y[a>>2]);y[b>>2]=a.getSeconds();y[b+4>>2]=a.getMinutes();y[b+8>>2]=a.getHours();
y[b+12>>2]=a.getDate();y[b+16>>2]=a.getMonth();y[b+20>>2]=a.getFullYear()-1900;y[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);y[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;y[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(2E3,6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;y[b+32>>2]=a;a=y[lc()+(a?4:0)>>2];y[b+40>>2]=a;return b},DYNAMICTOP_PTR:z,STACKTOP:Ga};var mc=e.asm(e.Aa,e.Ba,buffer);e.asm=mc;
var Ya=e.___emscripten_environ_constructor=function(){return e.asm.___emscripten_environ_constructor.apply(null,arguments)};e.___errno_location=function(){return e.asm.___errno_location.apply(null,arguments)};var kc=e.__get_daylight=function(){return e.asm.__get_daylight.apply(null,arguments)},jc=e.__get_timezone=function(){return e.asm.__get_timezone.apply(null,arguments)},lc=e.__get_tzname=function(){return e.asm.__get_tzname.apply(null,arguments)};
e._endXmp=function(){return e.asm._endXmp.apply(null,arguments)};var ec=e._free=function(){return e.asm._free.apply(null,arguments)};e._getMusicInfo=function(){return e.asm._getMusicInfo.apply(null,arguments)};e._getXmpCurrentPosition=function(){return e.asm._getXmpCurrentPosition.apply(null,arguments)};e._getXmpFrameInfo=function(){return e.asm._getXmpFrameInfo.apply(null,arguments)};e._getXmpLoopCount=function(){return e.asm._getXmpLoopCount.apply(null,arguments)};
e._getXmpMaxPosition=function(){return e.asm._getXmpMaxPosition.apply(null,arguments)};e._getXmpSampleRate=function(){return e.asm._getXmpSampleRate.apply(null,arguments)};e._getXmpSoundBuffer=function(){return e.asm._getXmpSoundBuffer.apply(null,arguments)};e._getXmpSoundBufferLen=function(){return e.asm._getXmpSoundBufferLen.apply(null,arguments)};e._initXmp=function(){return e.asm._initXmp.apply(null,arguments)};e._loadXmpModule=function(){return e.asm._loadXmpModule.apply(null,arguments)};
var ua=e._malloc=function(){return e.asm._malloc.apply(null,arguments)};e._playXmpFrame=function(){return e.asm._playXmpFrame.apply(null,arguments)};e._seekXmpPosition=function(){return e.asm._seekXmpPosition.apply(null,arguments)};e._startXmpPlayer=function(){return e.asm._startXmpPlayer.apply(null,arguments)};
var pa=e.stackAlloc=function(){return e.asm.stackAlloc.apply(null,arguments)},oa=e.stackRestore=function(){return e.asm.stackRestore.apply(null,arguments)},na=e.stackSave=function(){return e.asm.stackSave.apply(null,arguments)};e.asm=mc;
e.ccall=function(a,b,c,d){var f=e["_"+a];assert(f,"Cannot call unknown function "+a+", make sure it is exported");var g=[];a=0;if(d)for(var h=0;h<d.length;h++){var n=sa[c[h]];n?(0===a&&(a=na()),g[h]=n(d[h])):g[h]=d[h]}c=f.apply(null,g);c="string"===b?D(c):"boolean"===b?!!c:c;0!==a&&oa(a);return c};e.getMemory=va;e.Pointer_stringify=D;e.addRunDependency=Ta;e.removeRunDependency=Ua;e.FS_createFolder=Wb;e.FS_createPath=Xb;e.FS_createDataFile=Zb;e.FS_createPreloadedFile=cc;e.FS_createLazyFile=bc;
e.FS_createLink=$b;e.FS_createDevice=W;e.FS_unlink=Mb;Sa=function nc(){e.calledRun||oc();e.calledRun||(Sa=nc)};
function oc(){function a(){if(!e.calledRun&&(e.calledRun=!0,!ma)){ya||(ya=!0,Ka(Ma));Ka(Na);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Pa.unshift(a)}Ka(Pa)}}if(!(0<E)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Qa();Ka(La);0<E||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=oc;function t(a){if(e.onAbort)e.onAbort(a);void 0!==a?(fa(a),u(a),a=JSON.stringify(a)):a="";ma=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=t;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;oc();
  return {
	Module: Module,  // expose original Module
  };
})(window.spp_backend_state_XMP);
/*
 xmp_adapter.js: Adapts XMP backend to generic WebAudio/ScriptProcessor player.
 
 version 1.0
 
 	Copyright (C) 2015 Juergen Wothke

 LICENSE
 
 This library is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2.1 of the License, or (at
 your option) any later version. This library is distributed in the hope
 that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
*/
XMPBackendAdapter = (function(){ var $this = function () { 
		$this.base.call(this, backend_XMP.Module, 2);	
		this.isXmpAllocated= 0;
	}; 
	// XMP's sample buffer contains 2-byte integer sample data (i.e. must be rescaled) 
	// of 2 interleaved channels
	extend(EmsHEAP16BackendAdapter, $this, {  
		getAudioBuffer: function() {
			var ptr=  this.Module.ccall('getXmpSoundBuffer', 'number');			
			// make it a this.Module.HEAP16 pointer
			return ptr >> 1;	// 2 x 16 bit samples			
		},
		getAudioBufferLength: function() {
			var len= this.Module.ccall('getXmpSoundBufferLen', 'number') >>2;
			return len;
		},
		computeAudioSamples: function() {
			var status= this.Module.ccall('playXmpFrame', 'number');
			if (status != 0) return status;						// means "end song"
			
			return this.Module.ccall('getXmpLoopCount', 'number');	// >0 means "end song"
		},
		getMaxPlaybackPosition: function() { 
			return this.Module.ccall('getXmpMaxPosition', 'number');
		},
		getPlaybackPosition: function() {
			return this.Module.ccall('getXmpCurrentPosition', 'number');
		},
		seekPlaybackPosition: function(pos) { 
			return this.Module.ccall('seekXmpPosition', 'number', ['number'], [pos]);
		},

		getPathAndFilename: function(filename) {
			return ['/', filename];
		},
		registerFileData: function(pathFilenameArray, data) {
			return 0;	// not used in XMP
		},
		loadMusicData: function(sampleRate, path, filename, data, options) {
			var buf = this.Module._malloc(data.length);
			this.Module.HEAPU8.set(data, buf);
			
			var ret = this.Module.ccall('loadXmpModule', 'number', ['number', 'number', 'number'], [buf, data.length, sampleRate]);
			this.Module._free(buf);

			if (ret == 0) {			
				var inputSampleRate = this.Module.ccall('getXmpSampleRate', 'number');
				this.resetSampleRate(sampleRate, inputSampleRate); 
			}
			return ret;			
		},
		evalTrackOptions: function(options) {
			if (typeof options.timeout != 'undefined') {
				ScriptNodePlayer.getInstance().setPlaybackTimeout(options.timeout*1000);
			}
			var trackId= (typeof options.trackId != 'undefined') ? options.trackId : 0;	// only used for hvl			
			return this.Module.ccall('startXmpPlayer', 'number', ['number'], [trackId]);
		},				
		teardown: function() {
			if(this.isXmpAllocated)
				this.Module.ccall('endXmp', 'number');	// just in case
			this.Module.ccall('initXmp', 'number');
			this.isXmpAllocated= 1;
		},
		getSongInfoMeta: function() {
			return {title: String,
					player: String,
					tracks: String 
					};
		},
		updateSongInfo: function(filename, result) {
		// get song infos (so far only use some top level module infos)
			var numAttr= 3;
			var ret = this.Module.ccall('getMusicInfo', 'number');
			
			var array = this.Module.HEAP32.subarray(ret>>2, (ret>>2)+numAttr);
			result.title= this.Module.Pointer_stringify(array[0]);
			if (!result.title.length || (result.title ==="<unnamed>")) result.title= filename.replace(/^.*[\\\/]/, '').split('.').slice(0, -1).join('.');
			result.player= this.Module.Pointer_stringify(array[1]);
			result.tracks= this.Module.Pointer_stringify(array[2]);
		}
	});	return $this; })();
	